language: python

python:
  - "3.7"

env:
  - DJANGO_SETTINGS_MODULE=rainfalls.settings.dev

services:
  - postgresql

install:
  - pipenv install
  - pip install -r requirements/dev.txt

script:
  - pytest
