# Generated by Django 2.2.15 on 2020-09-14 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTerrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=100)),
                ('hectares', models.IntegerField()),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Field Terrain',
                'verbose_name_plural': 'Field Terrains',
            },
        ),
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('rain_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('field_terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rains', to='apps.FieldTerrain')),
            ],
            options={
                'verbose_name': 'Rain',
                'verbose_name_plural': 'Rains',
            },
        ),
    ]
