# Generated by Django 2.2.15 on 2020-09-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20200914_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rain',
            old_name='field_terrain',
            new_name='fieldterrain',
        ),
    ]
